### ISSUE TITLE
howTo install?

### ISSUE THREAD

**Issue by sl5net** [rcsaquino/rsautogui#1]
i not a rust user at the moment.
What i do first?
requirements to use rust scripts?
this? https://rust-script.org/#installation

**Comment by rcsaquino** [comment]
> i not a rust user at the moment. What i do first? requirements to use rust scripts? this? https://rust-script.org/#installation

Assuming you have rust installed and have a new cargo project ready, just type in your terminal from the project root `cargo add rsautogui`. If you prefer to do things manually, you can do so by adding `rsautogui = "*"` to your project dependencies in the `cargo.toml` file of your project.

If you don't have rust installed yet, or is unfamiliar with rust, I suggest you read the [rust book](https://doc.rust-lang.org/book) first. If you prefer videos you can watch [this series](https://www.youtube.com/watch?v=OX9HJsJUDxA&list=PLai5B987bZ9CoVR-QEIN9foz4QCJ0H2Y8) on youtube instead which is based on the rust book.
